services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  coordenador:
    build: ./coordenador
    ports:
      - "3000:3000"
    depends_on:
      - redis

  flask:
    build: ./flask
    environment:
      COORDINATOR_URL: "http://coordenador:3000"
    ports:
      - "5000:5000"
    depends_on:
      - coordenador
